export const restaurants = [
    {
      name: "The Hungry Fork",
      cuisines: ["Italian", "Pizza"],
      minDeliveryTime: 20,
      maxDeliveryTime: 40,
      deliveryFee: "Free",
      rating: 4.5,
      numReviews: 120,
      image: "assets/images/baked-salmon-futomaki.jpg",
      isOpenNow: true,
    },
    {
      name: "Spice Symphony",
      cuisines: ["Indian", "Vegetarian"],
      minDeliveryTime: 30,
      maxDeliveryTime: 50,
      deliveryFee: 3.99,
      rating: 4.2,
      numReviews: 85,
      image: "assets/images/sushi-hero.jpg",
      isOpenNow: true,
    },
    {
      name: "Sushi Delight",
      cuisines: ["Japanese", "Sushi"],
      minDeliveryTime: 25,
      maxDeliveryTime: 45,
      deliveryFee: 4.99,
      rating: 4.8,
      numReviews: 200,
      image: "assets/images/yamato-sushi.jpg",
      isOpenNow: true,
    },
    {
      name: "Burger Bros",
      cuisines: ["American", "Fast Food"],
      minDeliveryTime: 15,
      maxDeliveryTime: 30,
      deliveryFee: "Free",
      rating: 4.0,
      numReviews: 65,
      image: "assets/images/sushi-hero.jpg",
      isOpenNow: true,
    },
    {
      name: "Taco Fiesta",
      cuisines: ["Mexican", "Street Food"],
      minDeliveryTime: 20,
      maxDeliveryTime: 35,
      deliveryFee: 2.99,
      rating: 4.3,
      numReviews: 140,
      image: "assets/images/sushi-dream.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "Dragon Wok",
      cuisines: ["Chinese", "Asian"],
      minDeliveryTime: 30,
      maxDeliveryTime: 50,
      deliveryFee: 3.49,
      rating: 4.6,
      numReviews: 180,
      image: "assets/images/baked-salmon-futomaki.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "Urban Eats",
      cuisines: ["Fusion", "Healthy"],
      minDeliveryTime: 25,
      maxDeliveryTime: 40,
      deliveryFee: 3.99,
      rating: 4.4,
      numReviews: 95,
      image: "assets/images/sushi-dream.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "The Green Bowl",
      cuisines: ["Vegan", "Salads"],
      minDeliveryTime: 15,
      maxDeliveryTime: 25,
      deliveryFee: "Free",
      rating: 4.7,
      numReviews: 150,
      image: "assets/images/baked-salmon-futomaki.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "Pasta Palace",
      cuisines: ["Italian", "Pasta"],
      minDeliveryTime: 20,
      maxDeliveryTime: 40,
      deliveryFee: 2.49,
      rating: 4.2,
      numReviews: 70,
      image: "assets/images/bento-1.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "BBQ Haven",
      cuisines: ["American", "Barbecue"],
      minDeliveryTime: 30,
      maxDeliveryTime: 50,
      deliveryFee: 4.99,
      rating: 4.3,
      numReviews: 110,
      image: "assets/images/bento-1.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "Pho Real",
      cuisines: ["Vietnamese", "Soups"],
      minDeliveryTime: 25,
      maxDeliveryTime: 40,
      deliveryFee: "Free",
      rating: 4.5,
      numReviews: 130,
      image: "assets/images/sushi-craft.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "Curry House",
      cuisines: ["Indian", "Spicy"],
      minDeliveryTime: 30,
      maxDeliveryTime: 50,
      deliveryFee: 3.49,
      rating: 4.1,
      numReviews: 90,
      image: "assets/images/baked-salmon-futomaki.jpg",
      isOpenNow: false,
      address: 'Street 24',
    },
    {
      name: "Ramen Runners",
      cuisines: ["Japanese", "Ramen"],
      minDeliveryTime: 20,
      maxDeliveryTime: 35,
      deliveryFee: 2.99,
      rating: 4.7,
      numReviews: 160,
      image: "assets/images/baked-salmon-futomaki.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "Mediterranean Bliss",
      cuisines: ["Mediterranean", "Grill"],
      minDeliveryTime: 25,
      maxDeliveryTime: 45,
      deliveryFee: 3.99,
      rating: 4.4,
      numReviews: 105,
      image: "assets/images/sushi-craft.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "The Breakfast Spot",
      cuisines: ["Breakfast", "Brunch"],
      minDeliveryTime: 15,
      maxDeliveryTime: 25,
      deliveryFee: "Free",
      rating: 4.8,
      numReviews: 190,
      image: "assets/images/salmon-futomaki.jpg",
      isOpenNow: false,
      address: 'Street 24',
    },
    {
      name: "Dim Sum Garden",
      cuisines: ["Chinese", "Dim Sum"],
      minDeliveryTime: 30,
      maxDeliveryTime: 50,
      deliveryFee: 4.49,
      rating: 4.6,
      numReviews: 175,
      image: "assets/images/futomaki-ebi-tempura.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "Pizza Paradise",
      cuisines: ["Italian", "Pizza"],
      minDeliveryTime: 20,
      maxDeliveryTime: 40,
      deliveryFee: "Free",
      rating: 4.3,
      numReviews: 120,
      image: "assets/images/futomaki-ebi-tempura.jpg",
      isOpenNow: true,
      address: 'Street 24',
    },
    {
      name: "Tandoori Flames",
      cuisines: ["Indian", "Tandoori"],
      minDeliveryTime: 30,
      maxDeliveryTime: 50,
      deliveryFee: 3.99,
      rating: 4.2,
      numReviews: 80,
      image: "assets/images/dragon-uramaki.jpg",
      isOpenNow: false,
      address: 'Street 24',
    },
    {
      name: "Burger Blitz",
      cuisines: ["American", "Fast Food"],
      minDeliveryTime: 15,
      maxDeliveryTime: 30,
      deliveryFee: "Free",
      rating: 4.0,
      numReviews: 60,
      image: "assets/images/bento-2.jpg",
      isOpenNow: true,
      address: 'Street 11',
    },
    {
      name: "Sushi Sensation",
      cuisines: ["Japanese", "Sushi"],
      minDeliveryTime: 25,
      maxDeliveryTime: 45,
      deliveryFee: 4.99,
      rating: 4.9,
      numReviews: 210,
      image: "assets/images/bento-2.jpg",
      isOpenNow: true,
      address: 'Street 11',
    },
    {
        name: "Jade Dragon House",
        cuisines: ["Chinese", "Dim Sum"],
        minDeliveryTime: 25,
        maxDeliveryTime: 45,
        deliveryFee: 4.99,
        rating: 4.7,
        numReviews: 1283,
        image: "assets/images/futomaki-sake-roll.jpg",
        isOpenNow: false,
        address: 'Street 11',
      },
      {
        name: "Bella Pasta",
        cuisines: ["Italian", "Pizza"],
        minDeliveryTime: 30,
        maxDeliveryTime: 50,
        deliveryFee: 3.99,
        rating: 4.5,
        numReviews: 892,
        image: "assets/images/salmon-futomaki.jpg",
        isOpenNow: false,
        address: 'Street 11',
      },
      {
        name: "Sushi Master",
        cuisines: ["Japanese", "Sushi"],
        minDeliveryTime: 35,
        maxDeliveryTime: 55,
        deliveryFee: 5.99,
        rating: 4.8,
        numReviews: 2156,
        image: "assets/images/dragon-uramaki.jpg",
        isOpenNow: true,
        address: 'Street 11',
      },
      {
        name: "Taco Fiesta",
        cuisines: ["Mexican"],
        minDeliveryTime: 20,
        maxDeliveryTime: 40,
        deliveryFee: 2.99,
        rating: 4.3,
        numReviews: 567,
        image: "assets/images/yamato-sushi.jpg",
        isOpenNow: true,
        address: 'Street 11',
      },
      {
        name: "Mumbai Spice",
        cuisines: ["Indian", "Vegetarian"],
        minDeliveryTime: 30,
        maxDeliveryTime: 55,
        deliveryFee: 4.99,
        rating: 4.6,
        numReviews: 945,
        image: "assets/images/rainbow-set.jpg",
        isOpenNow: true,
        address: 'Street 11',
      },
      {
        name: "Burger Bros",
        cuisines: ["American", "Burgers"],
        minDeliveryTime: 15,
        maxDeliveryTime: 35,
        deliveryFee: 0,
        rating: 4.4,
        numReviews: 1567,
        image: "assets/images/futomaki-sake-roll.jpg",
        isOpenNow: false,
        address: 'Street 11',
      },
      {
        name: "Thai Orchid",
        cuisines: ["Thai", "Asian Fusion"],
        minDeliveryTime: 25,
        maxDeliveryTime: 45,
        deliveryFee: 3.99,
        rating: 4.5,
        numReviews: 782,
        image: "assets/images/yamato-sushi.jpg",
        isOpenNow: true,
        address: 'Street 11',
      },
      {
        name: "Mediterranean Delight",
        cuisines: ["Mediterranean", "Greek"],
        minDeliveryTime: 30,
        maxDeliveryTime: 50,
        deliveryFee: 4.99,
        rating: 4.7,
        numReviews: 623,
        image: "assets/images/rainbow-set.jpg",
        isOpenNow: false,
        address: 'Street 11',
      },
      {
        name: "Seoul Kitchen",
        cuisines: ["Korean", "BBQ"],
        minDeliveryTime: 35,
        maxDeliveryTime: 60,
        deliveryFee: 4.99,
        rating: 4.8,
        numReviews: 892,
        image: "assets/images/hosmomak-1.jpg",
        isOpenNow: false,
        address: 'Street 11',
      },
      {
        name: "Pho Express",
        cuisines: ["Vietnamese"],
        minDeliveryTime: 20,
        maxDeliveryTime: 40,
        deliveryFee: 2.99,
        rating: 4.4,
        numReviews: 456,
        image: "assets/images/rainbow-set.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "Wings & Things",
        cuisines: ["American", "Wings"],
        minDeliveryTime: 25,
        maxDeliveryTime: 45,
        deliveryFee: 0,
        rating: 4.2,
        numReviews: 789,
        image: "assets/images/hosmomak-1.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "Fresh Wok",
        cuisines: ["Chinese", "Asian"],
        minDeliveryTime: 20,
        maxDeliveryTime: 40,
        deliveryFee: 3.99,
        rating: 4.3,
        numReviews: 567,
        image: "assets/images/dragon-uramaki.jpg",
        isOpenNow: false,
        address: 'Street 89',
      },
      {
        name: "Pizza Paradise",
        cuisines: ["Italian", "Pizza"],
        minDeliveryTime: 25,
        maxDeliveryTime: 45,
        deliveryFee: 0,
        rating: 4.6,
        numReviews: 1432,
        image: "assets/images/point-sushi.jpg",
        isOpenNow: false,
        address: 'Street 89',
      },
      {
        name: "Veggie Valley",
        cuisines: ["Vegetarian", "Vegan"],
        minDeliveryTime: 25,
        maxDeliveryTime: 45,
        deliveryFee: 3.99,
        rating: 4.7,
        numReviews: 345,
        image: "assets/images/dragon-uramaki.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "Steakhouse Elite",
        cuisines: ["American", "Steakhouse"],
        minDeliveryTime: 35,
        maxDeliveryTime: 60,
        deliveryFee: 6.99,
        rating: 4.8,
        numReviews: 892,
        image: "assets/images/dragon-uramaki.jpg",
        isOpenNow: false,
        address: 'Street 89',
      },
      {
        name: "Falafel House",
        cuisines: ["Middle Eastern", "Mediterranean"],
        minDeliveryTime: 20,
        maxDeliveryTime: 40,
        deliveryFee: 3.99,
        rating: 4.5,
        numReviews: 567,
        image: "assets/images/hosmomak-2.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "Caribbean Flavors",
        cuisines: ["Caribbean", "Jamaican"],
        minDeliveryTime: 30,
        maxDeliveryTime: 50,
        deliveryFee: 4.99,
        rating: 4.6,
        numReviews: 234,
        image: "assets/images/rainbow-set.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "Ramen House",
        cuisines: ["Japanese", "Noodles"],
        minDeliveryTime: 25,
        maxDeliveryTime: 45,
        deliveryFee: 3.99,
        rating: 4.7,
        numReviews: 678,
        image: "assets/images/koneko-sushi.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "BBQ King",
        cuisines: ["BBQ", "American"],
        minDeliveryTime: 35,
        maxDeliveryTime: 60,
        deliveryFee: 5.99,
        rating: 4.8,
        numReviews: 1234,
        image: "assets/images/hosmomak-2.jpg",
        isOpenNow: false,
        address: 'Street 89',
      },
      {
        name: "Sandwich Studio",
        cuisines: ["Deli", "American"],
        minDeliveryTime: 15,
        maxDeliveryTime: 35,
        deliveryFee: 2.99,
        rating: 4.4,
        numReviews: 456,
        image: "assets/images/point-sushi.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "Spanish Tapas",
        cuisines: ["Spanish", "Mediterranean"],
        minDeliveryTime: 30,
        maxDeliveryTime: 50,
        deliveryFee: 4.99,
        rating: 4.6,
        numReviews: 345,
        image: "assets/images/koneko-sushi.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "Healthy Bowl",
        cuisines: ["Healthy", "Salads", "Bowls"],
        minDeliveryTime: 20,
        maxDeliveryTime: 40,
        deliveryFee: 3.99,
        rating: 4.5,
        numReviews: 789,
        image: "assets/images/katsu-sushi.jpg",
        isOpenNow: true,
        address: 'Street 89',
      },
      {
        name: "French Bistro",
        cuisines: ["French", "European"],
        minDeliveryTime: 35,
        maxDeliveryTime: 60,
        deliveryFee: 5.99,
        rating: 4.7,
        numReviews: 567,
        image: "assets/images/bento-3.jpg",
        isOpenNow: false,
        address: 'Street 89',
      },
      {
        name: "Seafood Shack",
        cuisines: ["Seafood", "American"],
        minDeliveryTime: 30,
        maxDeliveryTime: 55,
        deliveryFee: 4.99,
        rating: 4.6,
        numReviews: 890,
        image: "assets/images/katsu-sushi.jpg",
        isOpenNow: false,
        address: 'Street 89',
      },
      {
        name: "Street Tacos",
        cuisines: ["Mexican", "Street Food"],
        minDeliveryTime: 20,
        maxDeliveryTime: 40,
        deliveryFee: 0,
        rating: 4.4,
        numReviews: 678,
        image: "assets/images/bento-3.jpg",
        isOpenNow: true,
        address: 'Street 89',
      }
  ];  